language: java
jdk: openjdk13

os:
  - linux
  - osx

env:
    matrix:
      - TARGET="lab1"
      - TARGET="lab2"
      - TARGET="lab3"
      - TARGET="lab4"
      - TARGET="lab5"
      - TARGET="lab6"

script:
  - chmod u+x travis-script.sh
  - ./travis-script.sh
